DELETE FROM FactTrendingVideoStats CASCADE;
DELETE FROM DimTrendingDate CASCADE;
DELETE FROM DimVideo CASCADE;
DELETE FROM DimChannel CASCADE;
DELETE FROM DimRegion CASCADE;
DELETE FROM DimCategory CASCADE;