DROP TABLE IF EXISTS FactTrendingVideoStats CASCADE;
DROP TABLE IF EXISTS DimTrendingDate CASCADE;
DROP TABLE IF EXISTS DimVideo CASCADE;
DROP TABLE IF EXISTS DimChannel CASCADE;
DROP TABLE IF EXISTS DimRegion CASCADE;
DROP TABLE IF EXISTS DimCategory CASCADE;